steps:
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      docker build -t us-east1-docker.pkg.dev/sorbet-production/sorbet/sorbet-frontend-production:tag. .
    automapSubstitutions: true
images:
  - 'us-east1-docker.pkg.dev/sorbet-production/sorbet/sorbet-frontend-production:tag1'
options:
  logging: CLOUD_LOGGING_ONLY
