# Based on https://krzysztofzuraw.com/blog/2021/on-setting-up-next.js-with-docker-on-google-cloud/
# This build should be executed by a service account with the following roles:
# - Cloud Build Service Account
# - Secret Manager Secret Accessor
# - Cloud Run Developer
# - Service Account User
#
# For deploying the storybook to app engine, the SA need:
# - App Engine Deployer
# - App Engine Service Admin
steps:
  # Write the env file to the workspace so Next can bake variables into the build
  - id: write-env
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: ['-c', 'echo "$$sorbet_app_env_preview" > /workspace/.env']
    secretEnv: ['sorbet_app_env_preview']

  # Install dependencies and build Storybook
  # waitFor: ['-'] tells this to run in parallel with the main build
  - id: build-storybook
    waitFor: ['-']
    name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        corepack enable yarn
        yarn -v
        yarn install
        yarn build-storybook
    volumes:
      - name: storybook
        path: /workspace/.storybook/storybook-static

  # Deploy Storybook to App Engine as a non-promoted preview version
  # (does not take traffic away from the currently promoted version)
  - id: deploy-storybook-preview
    waitFor: ['build-storybook']
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - './.storybook/sb-deploy.yml'
      - '--ignore-file'
      - './.storybook/.sb-deploy-gcloudignore'
      - '--no-promote'
      - '--version'
      - 'preview-${_TAG}'
      - '-q'
    volumes:
      - name: storybook
        path: /workspace/.storybook/storybook-static

  # Build the image
  - id: build
    waitFor: ['write-env']
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag', '${_IMAGE}:${_TAG}', '--tag', '${_IMAGE}:latest', '.']

  # Push the image to artifact registry
  - id: push
    waitFor: ['build']
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}:${_TAG}']

  # Push the latest tag to artifact registry as well
  - id: push-latest
    waitFor: ['build']
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}:latest']

  # Deploy to Cloud Run (preview environment)
  - id: deploy-preview
    waitFor: ['push']
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sorbet-frontend-preview'
      - '--image'
      - '${_IMAGE}:${_TAG}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

substitutions:
  _TAG: '$COMMIT_SHA' # Remember to use --substitutions=_TAG="manual" if running with gcloud builds submit
  _IMAGE: 'us-east1-docker.pkg.dev/sorbet-production/sorbet/sorbet-frontend-preview'

images:
  - '${_IMAGE}:${_TAG}'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Pass env variables to the build from Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/sorbet-app-env-preview/versions/latest
      env: 'sorbet_app_env_preview'
