export const TOTAL_SKILLS: string[] = [
  'Graphic Design',
  'Illustration',
  'Animation',
  '3D Modeling',
  'Digital Painting',
  'Typography',
  'Logo Design',
  'UI Design (User Interface)',
  'UX Design (User Experience)',
  'Web Design',
  'Print Design',
  'Motion Graphics',
  'Video Editing',
  'Storyboarding',
  'Game Design',
  'Character Design',
  'Concept Art',
  'Product Design',
  'Industrial Design',
  'Architectural Design',
  'Fashion Design',
  'Costume Design',
  'Set Design',
  'Photography',
  'Photo Editing',
  'Cinematography',
  'Sound Design',
  'Music Composition',
  'Songwriting',
  'Singing',
  'Instrumental Music (e.g., piano, guitar)',
  'Music Production',
  'DJing',
  'Audio Editing',
  'Podcasting',
  'Voice Acting',
  'Writing (Fiction, Non-Fiction, Poetry)',
  'Copywriting',
  'Content Creation',
  'Blogging',
  'Screenwriting',
  'Playwriting',
  'Creative Writing',
  'Editing and Proofreading',
  'Public Speaking',
  'Storytelling',
  'Stand-Up Comedy',
  'Acting',
  'Improvisation',
  'Dance (e.g., Ballet, Hip-Hop, Contemporary)',
  'Choreography',
  'Circus Arts (e.g., juggling, acrobatics)',
  'Magic',
  'Puppetry',
  'Calligraphy',
  'Hand Lettering',
  'Paper Crafting',
  'Origami',
  'Floral Design',
  'Culinary Arts',
  'Cooking',
  'Baking',
  'Cake Decorating',
  'Mixology',
  'Sculpture',
  'Pottery',
  'Ceramics',
  'Glassblowing',
  'Woodworking',
  'Metalworking',
  'Leatherworking',
  'Textile Arts (e.g., weaving, knitting, crochet)',
  'Quilting',
  'Fashion Styling',
  'Makeup Artistry',
  'Hair Styling',
  'Nail Art',
  'Interior Design',
  'Feng Shui',
  'Landscape Design',
  'Digital Marketing',
  'Social Media Management',
  'SEO (Search Engine Optimization)',
  'Content Marketing',
  'Branding',
  'Public Relations',
  'Event Planning',
  'Project Management',
  'Data Visualization',
  'Information Architecture',
  'Infographic Design',
  'Virtual Assistance',
  'Language Translation',
  'Sign Language Interpretation',
  'Cultural Competence',
  'Cross-Cultural Communication',
  'Creative Consultation',
  'Intellectual Property Law',
  'Patent Illustration',
  'Story Consulting',
  'Trend Forecasting',
  'Rapid Prototyping',
  'Environmental Art',
  'Public Art Installation',
  'Street Art',
  'Land Art',
  'Graffiti Art',
  'Holography',
  'VJing (Visual Jockey)',
  'Storyboarding for Animation',
  'Environmental Animation',
  'Medical Illustration',
  'Technical Illustration',
  'Scientific Visualization',
  'Architectural Visualization',
  'Virtual Tour Creation',
  'UX Writing',
  'Technical Writing',
  'Creative Coding',
  'Generative Art',
  'Bio Art',
  'Wearable Technology Design',
  'Digital Sculpting',
  'VFX (Visual Effects)',
  'SFX (Special Effects)',
  'Miniature Model Making',
  'Robotics',
  'Drone Photography/Videography',
  'Science Communication',
  'Patent Writing',
  'Patent Illustration',
  'Renewable Energy Design',
  'Sustainable Design',
  'Eco-Friendly Packaging Design',
  'Social Innovation',
  'Civic Engagement Design',
  'Critical Thinking',
  'Problem Solving',
  'Data Visualization',
  'Digital Storytelling',
  'Cross-Platform Design',
  'Adaptive Design',
  'Game Testing',
  'Gamification Design',
  'Ethical Hacking',
  'Cybersecurity Awareness',
  'VR Prototyping',
  'Digital Archaeology',
  'Cryptocurrency Design',
  'Blockchain Art',
  'User Behavior Analysis',
  'Neuroaesthetics',
  'Art Therapy',
  'Creative Coaching',
  'Trend Analysis',
  'Visual Anthropology',
  'Futurism',
  'Remote Collaboration',
  'Digital Nomadism',
  'Remote Team Management',
  'Cultural Intelligence',
  'Social Media Analytics',
  'Influencer Marketing',
  'Cultural Marketing',
  'Experiential Marketing',
  'NFT (Non-Fungible Token) Art',
  'Digital Fashion Design',
  'Neurodesign',
  'Biofeedback Art',
  'Data Storytelling',
  'Ethical Design',
  'Inclusive Design',
  'Universal Design',
  'Experience Prototyping',
  'Blockchain Developer',
  'Smart Contract Developer',
  'Cryptocurrency Developer',
  'Solidity Programming',
  'Blockchain Architecture',
  'AR Developer (Augmented Reality)',
  'VR Developer (Virtual Reality)',
  '3D Printing Specialist',
  'Computer Vision Engineer',
  'Machine Learning Engineer',
  'Data Scientist',
  'Cybersecurity Specialist',
  'Ethical Hacker',
  'IoT (Internet of Things) Developer',
  'Robotics Engineer',
  'Automation Specialist',
  'Cloud Computing Architect',
  'DevOps Engineer',
  'Full Stack Developer',
  'Frontend Developer',
  'Backend Developer',
  'Mobile App Developer',
  'Game Developer',
  'UX/UI Developer',
  'Natural Language Processing (NLP) Engineer',
  'Computer Graphics Programmer',
  'Embedded Systems Developer',
  'Quantum Computing Specialist',
  'Bioinformatics Analyst',
  'Genetic Algorithm Developer',
];