export interface Category {
    code: string;
    label: string;
    accountType: 'individual' | 'business';
}

export const INDIVIDUAL_CATEGORIES: Category[] = [
    { code: 'employed', label: 'Employed', accountType: 'individual' },
    { code: 'retired', label: 'Retired', accountType: 'individual' },
    { code: 'self_employed', label: 'Self Employed', accountType: 'individual' },
    { code: 'student', label: 'Student', accountType: 'individual' },
    { code: 'unemployed', label: 'Unemployed', accountType: 'individual' },
];

export const BUSINESS_CATEGORIES: Category[] = [
    { code: 'academia_education', label: 'Academia & Education', accountType: 'business' },
    { code: 'accounting_bookkeeping', label: 'Accounting & Bookkeeping', accountType: 'business' },
    { code: 'adult_entertainment', label: 'Adult Entertainment', accountType: 'business' },
    { code: 'advertising_marketing', label: 'Advertising & Marketing', accountType: 'business' },
    { code: 'aerospace_aeronautical', label: 'Aerospace & Aeronautical', accountType: 'business' },
    { code: 'agriculture_farming', label: 'Agriculture & Farming', accountType: 'business' },
    { code: 'architecture_interior_design', label: 'Architecture & Interior Design', accountType: 'business' },
    { code: 'arms_defence_weapons', label: 'Arms, Defence & Weapons', accountType: 'business' },
    { code: 'artificial_intelligence', label: 'Artificial Intelligence', accountType: 'business' },
    { code: 'arts', label: 'Arts', accountType: 'business' },
    { code: 'ar_vr', label: 'AR/VR', accountType: 'business' },
    { code: 'automotive', label: 'Automotive', accountType: 'business' },
    { code: 'beauty_cosmetics', label: 'Beauty & Cosmetics', accountType: 'business' },
    { code: 'biotechnology', label: 'Biotechnology', accountType: 'business' },
    { code: 'cargo_logistics', label: 'Cargo & Logistics', accountType: 'business' },
    { code: 'charity_npo_ngo', label: 'Charity, NPO & NGO', accountType: 'business' },
    { code: 'chemicals', label: 'Chemicals', accountType: 'business' },
    { code: 'construction_civil_infrastructure', label: 'Construction, Civil & Infrastructure', accountType: 'business' },
    { code: 'consulting', label: 'Consulting', accountType: 'business' },
    { code: 'consumer_goods_services', label: 'Consumer Goods & Services', accountType: 'business' },
    { code: 'cryptocurrency_blockchain', label: 'Cryptocurrency & Blockchain', accountType: 'business' },
    { code: 'cybersecurity', label: 'Cybersecurity', accountType: 'business' },
    { code: 'dating', label: 'Dating', accountType: 'business' },
    { code: 'design', label: 'Design', accountType: 'business' },
    { code: 'ecommerce', label: 'E-commerce', accountType: 'business' },
    { code: 'energy_alternative_renewable', label: 'Energy - Alternative & Renewable', accountType: 'business' },
    { code: 'energy_oil_gas', label: 'Energy - Oil & Gas', accountType: 'business' },
    { code: 'entertainment_games_sports', label: 'Entertainment, Games & Sports', accountType: 'business' },
    { code: 'environmental_services', label: 'Environmental Services', accountType: 'business' },
    { code: 'fashion_non_luxury', label: 'Fashion (Non-Luxury)', accountType: 'business' },
    { code: 'film_cinematography_photography', label: 'Film, Cinematography & Photography', accountType: 'business' },
    { code: 'financial_services', label: 'Financial Services', accountType: 'business' },
    { code: 'fintech', label: 'Fintech', accountType: 'business' },
    { code: 'fmcg', label: 'FMCG', accountType: 'business' },
    { code: 'food_beverage_tobacco', label: 'Food, Beverage & Tobacco', accountType: 'business' },
    { code: 'freelance_self_employed', label: 'Freelance & Self Employed', accountType: 'business' },
    { code: 'gambling', label: 'Gambling', accountType: 'business' },
    { code: 'hardware_technology', label: 'Hardware Technology', accountType: 'business' },
    { code: 'healthcare', label: 'Healthcare', accountType: 'business' },
    { code: 'health_fitness', label: 'Health & Fitness', accountType: 'business' },
    { code: 'health_tech', label: 'Health Tech', accountType: 'business' },
    { code: 'hospitality_travel', label: 'Hospitality & Travel', accountType: 'business' },
    { code: 'import_export', label: 'Import & Export', accountType: 'business' },
    { code: 'information_technology', label: 'Information Technology', accountType: 'business' },
    { code: 'insurance', label: 'Insurance', accountType: 'business' },
    { code: 'international_relations_affairs', label: 'International Relations & Affairs', accountType: 'business' },
    { code: 'investment_ib_pe_hf_vc', label: 'Investment, IB, PE, HF & VC', accountType: 'business' },
    { code: 'legal_services', label: 'Legal Services', accountType: 'business' },
    { code: 'luxury_goods_fashion_jewellery', label: 'Luxury Goods, Fashion & Jewellery', accountType: 'business' },
    { code: 'machinery_industrial_engineering', label: 'Machinery & Industrial Engineering', accountType: 'business' },
    { code: 'manufacturing', label: 'Manufacturing', accountType: 'business' },
    { code: 'marijuana_recreational_drugs', label: 'Marijuana & Recreational Drugs', accountType: 'business' },
    { code: 'maritime', label: 'Maritime', accountType: 'business' },
    { code: 'marketplace_sharing_economy', label: 'Marketplace & Sharing Economy', accountType: 'business' },
    { code: 'media', label: 'Media', accountType: 'business' },
    { code: 'medicine_pharmaceutical', label: 'Medicine & Pharmaceutical', accountType: 'business' },
    { code: 'mining', label: 'Mining', accountType: 'business' },
    { code: 'precious_metals_stones', label: 'Precious Metals & Stones', accountType: 'business' },
    { code: 'professional_services', label: 'Professional Services', accountType: 'business' },
    { code: 'public_government_services', label: 'Public & Government Services', accountType: 'business' },
    { code: 'publishing', label: 'Publishing', accountType: 'business' },
    { code: 'railroads', label: 'Railroads', accountType: 'business' },
    { code: 'raw_materials_livestock', label: 'Raw Materials & Livestock', accountType: 'business' },
    { code: 'real_estate', label: 'Real Estate', accountType: 'business' },
    { code: 'research_think_tanks', label: 'Research & Think Tanks', accountType: 'business' },
    { code: 'retail_wholesale', label: 'Retail & Wholesale', accountType: 'business' },
    { code: 'sciences', label: 'Sciences', accountType: 'business' },
    { code: 'shipping_warehousing', label: 'Shipping & Warehousing', accountType: 'business' },
    { code: 'social_work', label: 'Social Work', accountType: 'business' },
    { code: 'software_technology_app_development', label: 'Software, Technology & App Development', accountType: 'business' },
    { code: 'telecommunications', label: 'Telecommunications', accountType: 'business' },
    { code: 'textiles', label: 'Textiles', accountType: 'business' },
    { code: 'transportation', label: 'Transportation', accountType: 'business' },
    { code: 'utilities', label: 'Utilities', accountType: 'business' },
    { code: 'waste_management', label: 'Waste Management', accountType: 'business' },
];

export const getAllCategories = (accountType: 'individual' | 'business'): Category[] => {
    return accountType === 'individual' ? INDIVIDUAL_CATEGORIES : BUSINESS_CATEGORIES;
};
